/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  OlympusStakingV2Helper,
  OlympusStakingV2HelperInterface,
} from "../OlympusStakingV2Helper";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_staking",
        type: "address",
      },
      {
        internalType: "address",
        name: "_OHM",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "OHM",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "stake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "staking",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class OlympusStakingV2Helper__factory {
  static readonly abi = _abi;
  static createInterface(): OlympusStakingV2HelperInterface {
    return new utils.Interface(_abi) as OlympusStakingV2HelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OlympusStakingV2Helper {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as OlympusStakingV2Helper;
  }
}
